name: konsole
base: core18
version: 17.12.3
description: Konsole version 17.12.3 . The last known terminal to mankind that can render variable width fonts (eg Tamil - தமிழ் correctly)
grade: stable
adopt-info: konsole

confinement: strict

apps:
  konsole:
    common-id: org.kde.konsole.desktop
    command: konsole
    extensions:
      - kde-neon
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - opengl
      - network
      - network-bind
      - pulseaudio

slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.konsole.desktop
    bus: session

parts:
  konsole:
    parse-info:
      - usr/share/metainfo/org.kde.konsole.appdata.xml
    plugin: cmake
    build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
    build-packages:
      - libmpfr-dev
      - libgmp-dev
      - kdoctools-dev
    stage-packages:
      - libmpfr6
      - libgmp10
    source: http://download.kde.org/stable/applications/17.12.3/src/konsole-17.12.3.tar.xz
    configflags:
      - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_TESTING=OFF"
      - "-DBUILD_TESTING=OFF"
      - "-DKDE_SKIP_TEST_SETTINGS=ON"
